/**
 * Onda 18 — Catálogo oficial do Feature Engine.
 *
 * Registro estático, imutável, versionado por deploy.
 * Sem banco. Sem I/O. Nenhum consumidor nesta onda.
 */
import type { Feature } from "../types/feature";

function f(input: Feature): Feature {
  return input;
}

export const FEATURE_CATALOG: readonly Feature[] = Object.freeze([
  f({
    id: "area-kids",
    slug: "area-kids",
    canonicalSlug: "area-kids",
    name: "Área Kids",
    description: "Espaço dedicado para crianças brincarem com segurança.",
    icon: "Baby",
    category: "estrutura",
    seoTitle: "Lugares com Área Kids",
    seoDescription:
      "Descubra restaurantes e bares com área kids, playground e espaço infantil.",
    indexable: true,
    enabled: true,
    weight: 70,
    synonyms: [
      "espaco kids",
      "brinquedoteca",
      "playground",
      "play kids",
      "espaco infantil",
      "kids",
      "parquinho",
    ],
    searchTerms: [
      "restaurante com area kids",
      "bar com espaco kids",
      "lugar com brinquedoteca",
      "restaurante para criancas",
    ],
  }),
  f({
    id: "pet-friendly",
    slug: "pet-friendly",
    canonicalSlug: "pet-friendly",
    name: "Pet Friendly",
    description: "Aceita animais de estimação no ambiente.",
    icon: "Dog",
    category: "publico",
    seoTitle: "Lugares Pet Friendly",
    seoDescription:
      "Bares e restaurantes que aceitam animais de estimação.",
    indexable: true,
    enabled: true,
    weight: 75,
    synonyms: [
      "aceita animais",
      "dog friendly",
      "pets",
      "animal",
      "cachorro",
      "aceita pet",
    ],
    searchTerms: [
      "bar pet friendly",
      "restaurante que aceita cachorro",
      "lugares dog friendly",
    ],
  }),
  f({
    id: "happy-hour",
    slug: "happy-hour",
    canonicalSlug: "happy-hour",
    name: "Happy Hour",
    description: "Promoções especiais em bebidas e petiscos após o expediente.",
    icon: "Beer",
    category: "experiencia",
    seoTitle: "Happy Hour",
    seoDescription: "Melhores happy hours com promoções e ambiente descontraído.",
    indexable: true,
    enabled: true,
    weight: 80,
    synonyms: ["hh", "promocao chopp", "happy"],
    searchTerms: ["happy hour", "happy hour perto de mim", "bar com happy hour"],
  }),
  f({
    id: "musica-ao-vivo",
    slug: "musica-ao-vivo",
    canonicalSlug: "musica-ao-vivo",
    name: "Música ao vivo",
    description: "Apresentações musicais ao vivo com bandas ou artistas solo.",
    icon: "Music",
    category: "entretenimento",
    seoTitle: "Lugares com Música ao Vivo",
    seoDescription:
      "Bares e restaurantes com música ao vivo, bandas e artistas.",
    indexable: true,
    enabled: true,
    weight: 85,
    synonyms: ["show ao vivo", "banda", "musica", "acustico", "voz e violao"],
    searchTerms: [
      "musica ao vivo",
      "bar com banda",
      "restaurante com show",
      "voz e violao",
    ],
  }),
  f({
    id: "telao-esportivo",
    slug: "telao-esportivo",
    canonicalSlug: "telao-esportivo",
    name: "Telão esportivo",
    description: "Transmissão de jogos e eventos esportivos em telão.",
    icon: "Tv",
    category: "entretenimento",
    seoTitle: "Lugares com Telão Esportivo",
    seoDescription:
      "Bares que transmitem jogos ao vivo em telão para assistir com amigos.",
    indexable: true,
    enabled: true,
    weight: 70,
    synonyms: ["telao", "tv", "transmite jogo", "assiste jogo"],
    searchTerms: ["bar com telao", "onde assistir o jogo", "telao futebol"],
  }),
  f({
    id: "wifi",
    slug: "wifi",
    canonicalSlug: "wifi",
    name: "Wi-Fi",
    description: "Internet sem fio disponível para clientes.",
    icon: "Wifi",
    category: "estrutura",
    seoTitle: "Lugares com Wi-Fi",
    seoDescription: "Estabelecimentos com Wi-Fi gratuito para clientes.",
    indexable: false,
    enabled: true,
    weight: 30,
    synonyms: ["internet", "wireless", "wi fi"],
    searchTerms: ["cafe com wifi", "restaurante com internet"],
  }),
  f({
    id: "estacionamento",
    slug: "estacionamento",
    canonicalSlug: "estacionamento",
    name: "Estacionamento",
    description: "Estacionamento próprio ou conveniado.",
    icon: "ParkingSquare",
    category: "servicos",
    seoTitle: "Lugares com Estacionamento",
    seoDescription: "Bares e restaurantes com estacionamento próprio.",
    indexable: false,
    enabled: true,
    weight: 40,
    synonyms: ["estaciona", "vaga", "valet", "manobrista"],
    searchTerms: ["restaurante com estacionamento", "bar com valet"],
  }),
  f({
    id: "area-externa",
    slug: "area-externa",
    canonicalSlug: "area-externa",
    name: "Área externa",
    description: "Ambiente ao ar livre, varanda, deck ou jardim.",
    icon: "Trees",
    category: "ambiente",
    seoTitle: "Lugares com Área Externa",
    seoDescription:
      "Restaurantes e bares com varanda, deck, jardim e área ao ar livre.",
    indexable: true,
    enabled: true,
    weight: 65,
    synonyms: ["varanda", "deck", "jardim", "ao ar livre", "open air"],
    searchTerms: ["restaurante com area externa", "bar ao ar livre"],
  }),
  f({
    id: "ar-condicionado",
    slug: "ar-condicionado",
    canonicalSlug: "ar-condicionado",
    name: "Ambiente climatizado",
    description: "Ar-condicionado em todo o ambiente.",
    icon: "Snowflake",
    category: "estrutura",
    seoTitle: "Lugares Climatizados",
    seoDescription: "Estabelecimentos com ar-condicionado e ambiente climatizado.",
    indexable: false,
    enabled: true,
    weight: 25,
    synonyms: ["ar condicionado", "climatizado", "refrigerado"],
    searchTerms: ["restaurante com ar condicionado"],
  }),
  f({
    id: "delivery",
    slug: "delivery",
    canonicalSlug: "delivery",
    name: "Delivery",
    description: "Entrega de pedidos em domicílio.",
    icon: "Bike",
    category: "servicos",
    seoTitle: "Delivery",
    seoDescription: "Restaurantes com delivery e entrega em casa.",
    indexable: false,
    enabled: true,
    weight: 45,
    synonyms: ["entrega", "tele entrega", "ifood"],
    searchTerms: ["restaurante delivery", "comida em casa"],
  }),
  f({
    id: "retirada",
    slug: "retirada",
    canonicalSlug: "retirada",
    name: "Retirada",
    description: "Pedido para retirar no local (takeaway).",
    icon: "ShoppingBag",
    category: "servicos",
    seoTitle: "Retirada no local",
    seoDescription: "Restaurantes com opção de retirada e takeaway.",
    indexable: false,
    enabled: true,
    weight: 20,
    synonyms: ["takeaway", "take away", "para viagem", "para retirar"],
    searchTerms: ["comida para retirar", "pedido para viagem"],
  }),
  f({
    id: "reserva",
    slug: "reserva",
    canonicalSlug: "reserva",
    name: "Reserva",
    description: "Aceita reserva antecipada de mesa.",
    icon: "CalendarCheck",
    category: "servicos",
    seoTitle: "Aceita Reserva",
    seoDescription: "Restaurantes e bares que aceitam reserva antecipada.",
    indexable: false,
    enabled: true,
    weight: 55,
    synonyms: ["reservar mesa", "aceita reserva", "booking"],
    searchTerms: ["restaurante que aceita reserva", "reservar mesa"],
  }),
  f({
    id: "lista-vip",
    slug: "lista-vip",
    canonicalSlug: "lista-vip",
    name: "Lista VIP",
    description: "Lista VIP disponível para eventos.",
    icon: "Star",
    category: "servicos",
    seoTitle: "Lista VIP",
    seoDescription: "Baladas e eventos com lista VIP.",
    indexable: false,
    enabled: true,
    weight: 60,
    synonyms: ["vip", "camarote", "guest list"],
    searchTerms: ["lista vip", "camarote"],
  }),
  f({
    id: "carta-de-vinhos",
    slug: "carta-de-vinhos",
    canonicalSlug: "carta-de-vinhos",
    name: "Carta de vinhos",
    description: "Ampla seleção de vinhos e rótulos especiais.",
    icon: "Wine",
    category: "bebidas",
    seoTitle: "Lugares com Carta de Vinhos",
    seoDescription: "Restaurantes com carta de vinhos e rótulos selecionados.",
    indexable: true,
    enabled: true,
    weight: 65,
    synonyms: ["vinho", "wine", "adega", "vinicola", "sommelier"],
    searchTerms: ["restaurante com carta de vinhos", "vinho"],
  }),
  f({
    id: "drinks",
    slug: "drinks",
    canonicalSlug: "drinks",
    name: "Drinks",
    description: "Coquetelaria autoral e drinks especiais.",
    icon: "Martini",
    category: "bebidas",
    seoTitle: "Lugares com Drinks Autorais",
    seoDescription: "Bares com coquetelaria autoral e drinks especiais.",
    indexable: true,
    enabled: true,
    weight: 75,
    synonyms: ["coqueteis", "cocktail", "mixologia", "coquetel autoral"],
    searchTerms: ["drinks", "bar de coqueteis", "coquetelaria autoral"],
  }),
  f({
    id: "chopp-artesanal",
    slug: "chopp-artesanal",
    canonicalSlug: "chopp-artesanal",
    name: "Chopp artesanal",
    description: "Variedade de chopes e cervejas artesanais.",
    icon: "Beer",
    category: "bebidas",
    seoTitle: "Chopp Artesanal",
    seoDescription:
      "Bares com chopp e cerveja artesanal de rótulos locais.",
    indexable: true,
    enabled: true,
    weight: 70,
    synonyms: ["chope", "cerveja artesanal", "craft beer", "cervejaria"],
    searchTerms: ["chopp artesanal", "cervejaria", "cerveja artesanal"],
  }),
  f({
    id: "buffet",
    slug: "buffet",
    canonicalSlug: "buffet",
    name: "Buffet",
    description: "Buffet livre ou por peso.",
    icon: "UtensilsCrossed",
    category: "comida",
    seoTitle: "Buffet",
    seoDescription: "Restaurantes com buffet livre ou por quilo.",
    indexable: true,
    enabled: true,
    weight: 55,
    synonyms: ["self service", "por quilo", "kilo", "livre"],
    searchTerms: ["buffet", "restaurante por quilo"],
  }),
  f({
    id: "rodizio",
    slug: "rodizio",
    canonicalSlug: "rodizio",
    name: "Rodízio",
    description: "Rodízio à vontade de carnes, pizza, sushi ou pratos.",
    icon: "UtensilsCrossed",
    category: "comida",
    seoTitle: "Rodízio",
    seoDescription: "Restaurantes com rodízio à vontade.",
    indexable: true,
    enabled: true,
    weight: 70,
    synonyms: ["a vontade", "all you can eat"],
    searchTerms: ["rodizio", "rodizio de pizza", "rodizio japones"],
  }),
  f({
    id: "almoco-executivo",
    slug: "almoco-executivo",
    canonicalSlug: "almoco-executivo",
    name: "Almoço executivo",
    description: "Menu executivo para almoço rápido durante a semana.",
    icon: "Briefcase",
    category: "comida",
    seoTitle: "Almoço Executivo",
    seoDescription:
      "Restaurantes com menu executivo para o almoço durante a semana.",
    indexable: true,
    enabled: true,
    weight: 50,
    synonyms: ["pf", "prato feito", "menu executivo", "prato do dia"],
    searchTerms: ["almoco executivo", "menu executivo", "almoco rapido"],
  }),
  f({
    id: "vegano",
    slug: "vegano",
    canonicalSlug: "vegano",
    name: "Vegano",
    description: "Opções veganas no cardápio.",
    icon: "Leaf",
    category: "comida",
    seoTitle: "Restaurantes Veganos",
    seoDescription: "Restaurantes com opções veganas e menu plant-based.",
    indexable: true,
    enabled: true,
    weight: 65,
    synonyms: ["plant based", "vegan"],
    searchTerms: ["restaurante vegano", "comida vegana"],
  }),
  f({
    id: "vegetariano",
    slug: "vegetariano",
    canonicalSlug: "vegetariano",
    name: "Vegetariano",
    description: "Opções vegetarianas no cardápio.",
    icon: "Salad",
    category: "comida",
    seoTitle: "Restaurantes Vegetarianos",
    seoDescription: "Restaurantes com opções vegetarianas.",
    indexable: true,
    enabled: true,
    weight: 60,
    synonyms: ["veggie", "sem carne"],
    searchTerms: ["restaurante vegetariano", "comida vegetariana"],
  }),
  f({
    id: "sem-gluten",
    slug: "sem-gluten",
    canonicalSlug: "sem-gluten",
    name: "Sem glúten",
    description: "Opções sem glúten no cardápio.",
    icon: "WheatOff",
    category: "comida",
    seoTitle: "Sem Glúten",
    seoDescription: "Restaurantes com opções sem glúten (gluten free).",
    indexable: true,
    enabled: true,
    weight: 50,
    synonyms: ["gluten free", "celiaco"],
    searchTerms: ["restaurante sem gluten", "comida gluten free"],
  }),
  f({
    id: "hamburguer-artesanal",
    slug: "hamburguer-artesanal",
    canonicalSlug: "hamburguer-artesanal",
    name: "Hambúrguer artesanal",
    description: "Hambúrgueres artesanais com blends autorais.",
    icon: "Beef",
    category: "comida",
    seoTitle: "Hambúrguer Artesanal",
    seoDescription: "Hamburguerias com blends autorais e receitas artesanais.",
    indexable: true,
    enabled: true,
    weight: 75,
    synonyms: ["burger", "hamburgueria", "smash", "smash burger"],
    searchTerms: ["hamburguer artesanal", "hamburgueria", "burger"],
  }),
  f({
    id: "pizza",
    slug: "pizza",
    canonicalSlug: "pizza",
    name: "Pizza",
    description: "Pizzarias com forno a lenha ou napolitana.",
    icon: "Pizza",
    category: "comida",
    seoTitle: "Pizzarias",
    seoDescription: "Pizzarias com forno a lenha, napolitana e artesanal.",
    indexable: true,
    enabled: true,
    weight: 75,
    synonyms: ["pizzaria", "forno a lenha", "napolitana"],
    searchTerms: ["pizzaria", "pizza"],
  }),
  f({
    id: "sushi",
    slug: "sushi",
    canonicalSlug: "sushi",
    name: "Sushi",
    description: "Culinária japonesa com sushi, sashimi e temakis.",
    icon: "Fish",
    category: "comida",
    seoTitle: "Sushi e Comida Japonesa",
    seoDescription: "Restaurantes japoneses com sushi, sashimi e temaki.",
    indexable: true,
    enabled: true,
    weight: 75,
    synonyms: ["japones", "temaki", "sashimi", "japa"],
    searchTerms: ["sushi", "restaurante japones", "temakeria"],
  }),
  f({
    id: "massas",
    slug: "massas",
    canonicalSlug: "massas",
    name: "Massas",
    description: "Cantinas e restaurantes especializados em massas.",
    icon: "Utensils",
    category: "comida",
    seoTitle: "Massas e Cantinas",
    seoDescription: "Cantinas italianas e restaurantes de massas artesanais.",
    indexable: true,
    enabled: true,
    weight: 60,
    synonyms: ["italiano", "cantina", "macarrao", "nhoque", "pasta"],
    searchTerms: ["restaurante de massas", "cantina italiana"],
  }),
  f({
    id: "churrasco",
    slug: "churrasco",
    canonicalSlug: "churrasco",
    name: "Churrasco",
    description: "Churrascarias, parrilla e casas de carne.",
    icon: "Flame",
    category: "comida",
    seoTitle: "Churrascarias",
    seoDescription: "Churrascarias, parrilla e casas de carne.",
    indexable: true,
    enabled: true,
    weight: 70,
    synonyms: ["churrascaria", "parrilla", "carne", "steakhouse"],
    searchTerms: ["churrascaria", "churrasco", "carne"],
  }),
  f({
    id: "adega",
    slug: "adega",
    canonicalSlug: "adega",
    name: "Adega",
    description: "Adega própria com rótulos especiais.",
    icon: "Wine",
    category: "bebidas",
    seoTitle: "Adegas",
    seoDescription: "Restaurantes com adega própria e rótulos selecionados.",
    indexable: false,
    enabled: true,
    weight: 40,
    synonyms: ["cave", "wine cellar"],
    searchTerms: ["adega"],
  }),
  f({
    id: "instagramavel",
    slug: "instagramavel",
    canonicalSlug: "instagramavel",
    name: "Espaço instagramável",
    description: "Ambiente com decoração perfeita para fotos.",
    icon: "Camera",
    category: "ambiente",
    seoTitle: "Lugares Instagramáveis",
    seoDescription:
      "Bares e restaurantes com decoração perfeita para fotos e redes sociais.",
    indexable: true,
    enabled: true,
    weight: 65,
    synonyms: ["fotografavel", "decorado", "photo spot"],
    searchTerms: ["lugar instagramavel", "restaurante para fotos"],
  }),
  f({
    id: "romantico",
    slug: "romantico",
    canonicalSlug: "romantico",
    name: "Ambiente romântico",
    description: "Clima intimista, ideal para casais.",
    icon: "Heart",
    category: "ambiente",
    seoTitle: "Restaurantes Românticos",
    seoDescription: "Restaurantes com ambiente romântico para jantar a dois.",
    indexable: true,
    enabled: true,
    weight: 75,
    synonyms: ["a dois", "casal", "intimista", "date"],
    searchTerms: ["restaurante romantico", "jantar a dois", "date"],
  }),
  f({
    id: "familiar",
    slug: "familiar",
    canonicalSlug: "familiar",
    name: "Ambiente familiar",
    description: "Ideal para ir com a família e crianças.",
    icon: "Users",
    category: "publico",
    seoTitle: "Restaurantes para Família",
    seoDescription: "Restaurantes com ambiente familiar, ideais para ir com crianças.",
    indexable: true,
    enabled: true,
    weight: 70,
    synonyms: ["familia", "criancas", "family friendly"],
    searchTerms: ["restaurante para familia", "restaurante familiar"],
  }),
  f({
    id: "para-grupos",
    slug: "para-grupos",
    canonicalSlug: "para-grupos",
    name: "Ideal para grupos",
    description: "Mesas grandes e ambiente ideal para grupos.",
    icon: "Users",
    category: "publico",
    seoTitle: "Lugares para Grupos",
    seoDescription: "Restaurantes e bares ideais para grupos e turmas.",
    indexable: true,
    enabled: true,
    weight: 55,
    synonyms: ["turma", "grande grupo", "amigos"],
    searchTerms: ["restaurante para grupos", "bar para grupo grande"],
  }),
  f({
    id: "para-aniversarios",
    slug: "para-aniversarios",
    canonicalSlug: "para-aniversarios",
    name: "Ideal para aniversários",
    description: "Recebe grupos de aniversário e comemorações.",
    icon: "PartyPopper",
    category: "experiencia",
    seoTitle: "Lugares para Aniversário",
    seoDescription: "Restaurantes e bares ideais para comemorar aniversário.",
    indexable: true,
    enabled: true,
    weight: 65,
    synonyms: ["niver", "aniversario", "comemorar"],
    searchTerms: ["restaurante para aniversario", "bar para comemorar niver"],
  }),
  f({
    id: "para-reunioes",
    slug: "para-reunioes",
    canonicalSlug: "para-reunioes",
    name: "Ideal para reuniões",
    description: "Ambiente adequado para reuniões de trabalho.",
    icon: "Briefcase",
    category: "experiencia",
    seoTitle: "Lugares para Reunião",
    seoDescription: "Restaurantes ideais para reunião de negócios.",
    indexable: false,
    enabled: true,
    weight: 35,
    synonyms: ["business", "corporativo", "trabalho"],
    searchTerms: ["restaurante para reuniao", "almoco de negocios"],
  }),
  f({
    id: "aceita-cartao",
    slug: "aceita-cartao",
    canonicalSlug: "aceita-cartao",
    name: "Aceita cartão",
    description: "Aceita pagamento com cartão de crédito e débito.",
    icon: "CreditCard",
    category: "pagamento",
    seoTitle: "Aceita Cartão",
    seoDescription: "Estabelecimentos que aceitam pagamento com cartão.",
    indexable: false,
    enabled: true,
    weight: 20,
    synonyms: ["credito", "debito", "visa", "master"],
    searchTerms: ["aceita cartao"],
  }),
  f({
    id: "pix",
    slug: "pix",
    canonicalSlug: "pix",
    name: "Pix",
    description: "Aceita pagamento via Pix.",
    icon: "QrCode",
    category: "pagamento",
    seoTitle: "Aceita Pix",
    seoDescription: "Estabelecimentos que aceitam pagamento via Pix.",
    indexable: false,
    enabled: true,
    weight: 15,
    synonyms: ["pix qr", "pagamento pix"],
    searchTerms: ["aceita pix"],
  }),
  f({
    id: "acessibilidade",
    slug: "acessibilidade",
    canonicalSlug: "acessibilidade",
    name: "Acessibilidade",
    description: "Estrutura acessível para pessoas com deficiência.",
    icon: "Accessibility",
    category: "acessibilidade",
    seoTitle: "Lugares Acessíveis",
    seoDescription:
      "Estabelecimentos com estrutura acessível: rampa, banheiro adaptado e cadeirante.",
    indexable: true,
    enabled: true,
    weight: 60,
    synonyms: ["rampa", "cadeirante", "pcd", "adaptado"],
    searchTerms: ["restaurante acessivel", "bar com rampa", "banheiro adaptado"],
  }),
] as const);

export const FEATURE_CATEGORIES: readonly {
  id: import("../types/feature").FeatureCategory;
  label: string;
}[] = Object.freeze([
  { id: "ambiente", label: "Ambiente" },
  { id: "publico", label: "Público" },
  { id: "comida", label: "Comida" },
  { id: "bebidas", label: "Bebidas" },
  { id: "servicos", label: "Serviços" },
  { id: "estrutura", label: "Estrutura" },
  { id: "experiencia", label: "Experiência" },
  { id: "entretenimento", label: "Entretenimento" },
  { id: "acessibilidade", label: "Acessibilidade" },
  { id: "pagamento", label: "Pagamento" },
] as const);
