// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
var list_events_default = defineTool({
  name: "list_events",
  title: "List upcoming events",
  description: "List upcoming published events on Roxou (nightlife discovery). Optionally filter by city.",
  inputSchema: {
    city: z.string().optional().describe("City name filter (e.g. 'Presidente Prudente')."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Supabase env not configured." }], isError: true };
    }
    const supabase = createClient(url, key, { auth: { persistSession: false } });
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    let q = supabase.from("events").select("id,title,city,date_time,venue_name,slug").eq("status", "published").gte("date_time", nowIso).order("date_time", { ascending: true }).limit(limit ?? 10);
    if (city) q = q.ilike("city", `%${city}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-partners.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
var list_partners_default = defineTool2({
  name: "list_partners",
  title: "List partners (venues)",
  description: "List venues/partners registered on Roxou. Optionally filter by city or type (bar, club, restaurant, etc.).",
  inputSchema: {
    city: z2.string().optional().describe("City filter."),
    type: z2.string().optional().describe("Partner type filter."),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, type, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Supabase env not configured." }], isError: true };
    }
    const supabase = createClient2(url, key, { auth: { persistSession: false } });
    let q = supabase.from("partners").select("id,name,slug,city,type,logo_url").order("name", { ascending: true }).limit(limit ?? 20);
    if (city) q = q.ilike("city", `%${city}%`);
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { partners: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-events.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
var search_events_default = defineTool3({
  name: "search_events",
  title: "Search events",
  description: "Full-text search over published Roxou events by title, venue or description keyword.",
  inputSchema: {
    query: z3.string().min(1).describe("Search keywords."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Supabase env not configured." }], isError: true };
    }
    const supabase = createClient3(url, key, { auth: { persistSession: false } });
    const pattern = `%${query}%`;
    const { data, error } = await supabase.from("events").select("id,title,city,date_time,venue_name,slug").eq("status", "published").or(`title.ilike.${pattern},venue_name.ilike.${pattern},description.ilike.${pattern}`).order("date_time", { ascending: true }).limit(limit ?? 15);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "roxou-mcp",
  title: "Roxou MCP",
  version: "0.1.0",
  instructions: "Roxou is a nightlife discovery platform for cities in the interior of S\xE3o Paulo, Brazil. Use `list_events` to browse upcoming published events (optionally by city), `search_events` for keyword queries, and `list_partners` to discover venues/bars/clubs. All data is public read-only.",
  tools: [list_events_default, list_partners_default, search_events_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
